server:
  port: 8280

spring:
  application:
    name: zuulsvr
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://127.0.0.1:8282
eureka:
  instance:
    prefer-ip-address: true

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8180/eureka/
zuul:
  sensitive-headers: Cookie,Set-Cookie
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    routes:
      enabled: true

