wiki:
  cccp:
    name: licensingservice
    version: default
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/microservice
    username: postgres
    password: 331107
  redis:
    host: 192.168.133.129
    port: 6379
    database: 0
    timeout: 3000