server:
  port: 8188

spring:
  application:
    name: authservice

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8180/eureka/

  instance:
    prefer-ip-address: true
