wiki:
  cccp:
    name: organizationservice
    version: default
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/microservice
    username: postgres
    password: 331107
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://127.0.0.1:8282